//  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

using System.Collections.Generic;

List<int> sequence = new List<int>() { 1, 2 };

do
{
    int next = sequence[sequence.Count-1] + sequence[sequence.Count-2];
    sequence.Add(next);
} while ( sequence [sequence.Count-1] < 4000000 );

int sum = 0;
foreach (var x in sequence)
{
    sum += x % 2 == 0 ? x : 0;
}
Console.WriteLine($"Sum is {sum}");